name: New Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  run-build:
    uses: ./.github/workflows/build.yml
    with:
      tag_name: ${{ github.event.release.tag_name }}

  upload-to-release:
    needs: run-build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Installers
        uses: actions/download-artifact@v4
        with:
          path: llcw
          pattern: "*-*"
          merge-multiple: true

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: llcw/*
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}